name: firebase_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.7.0
  firebase_auth: ^5.3.2
  cloud_firestore: ^5.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/home1.png
    - assets/images/home2.png
    - assets/images/home3.png
    - assets/images/home4.png
    - assets/images/home5.png
    - assets/images/home6.png
    - assets/images/home7.png
    - assets/images/home8.png
    - assets/images/emotions.png
    - assets/images/happiness.png
    - assets/images/disgust.png
    - assets/images/sadness.png
    - assets/images/surprise.png
    - assets/images/exhaustion.png
    - assets/images/apprehension.png
    - assets/images/anger.png
    - assets/images/fear.png
    - assets/images/smile_green.png
    - assets/images/smile_light_green.png
    - assets/images/neutral_yellow.png
    - assets/images/sad_orange.png
    - assets/images/sad_red.png
    - assets/images/hand.png
    - assets/images/show.png

